name: Trigger Credentials Update

on:
  schedule:
    # Run daily at 03:12 and 15:12
    # Reasons? no reasons
    - cron: '12 3,15 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to renew auth credentials
        run: |
          curl --request POST \
          --url 'https://qatar22.vercel.app/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'