name: Trigger Credentials Update

on:
  schedule:
    # Run daily at 03:12 and 15:12 in november and december
    # (Twice a day should be enough to refresh the api access token)
    # https://crontab.guru/#12_3,15_*_11,12_*
    - cron: '12 3,15 * 11,12 *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to renew auth credentials
        run: |
          curl --request POST \
          --url 'https://qatar22.vercel.app/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'